name = "usc-asbuilt-workspace"
pages_build_output_dir = "."
compatibility_date = "2026-06-16"

[vars]
ASBUILT_ADMIN_EMAILS = "gamecockrk@gmail.com,ryan.kelly@telcomsc.com,wallace.reese@telcomsc.com"

[[kv_namespaces]]
binding = "ASBUILT_MAPS"
id = "ce6553562133492ead6eb6ea721e80b3"

[[kv_namespaces]]
binding = "ASBUILT_FIELDS"
id = "20973da05c324196ae5fb6ec1892b3e8"

[[kv_namespaces]]
binding = "ASBUILT_DOCS"
id = "ec86844b9c2e4840a9406a1196893ab2"
